---
- name: reload sysctl.conf
  command: /sbin/sysctl -p

- name: flush routes
  command: /sbin/sysctl -w net.ipv4.route.flush=1

- name: reload iptables
  command: /sbin/iptables-restore /etc/iptables.restore
